# Generated by Django 4.1.7 on 2023-03-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='doj',
            new_name='date_of_joining',
        ),
    ]
